Docs/templates
hamlet-io/.github pull request #2
Opened 2021-03-09 07:27 UTC by RossMurr4y

## Description

  Includes the following changes to the _Pull Request_ template:
  
  * updates _types of changes_ section:
    * change to bullet-point where the unapplicable types can be deleted, rather than "checked"
    * Renames section to _Intent of Change_ to provide a very quick summary of what to expect
    * Moved ahead of the description section as it will most commonly be only one point and will act as a change classification system
    * add a "Documentation" bullet point
  * updates _Checklist_ section:
    * change to bullet-point to act in place of a reminder and guidance, but require no action
    * replace existing options with most-applicable reminders
      * anything specific that should be added to this list should instead be incorporated into the CONTRIBUTING.md file, where it can be elaborated on without creating noise to every ticket

* Creates a new template for requesting of new or updated documentation

## Motivation and Context

Current tick-box system for PR's is largely skipped over and unhelpful.

A checklist provides a reminder, something for reviewers to direct people to and guides people towards the contributor guide. From there we have a central place to construct a more verbose guide.

Issues requesting changes to documentation have unique requirements and should be easily identifiable from bugs/feature requests

## How Has This Been Tested?

n/a

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions

- [x] None

## Checklist:

- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] None of the above.

2021-03-10 03:20 UTC, RossMurr4y commented
removed the new template type and submitted separate PR for this that was done through the GUI

2021-03-10 03:31 UTC, roleyfoley requested changes

2021-03-10 03:31 UTC, roleyfoley commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--- What types of changes does your code introduce?  -->
I think we can remove that line. Would be nice to keep the comments to a minimum otherwise its a lot to remove each time

2021-03-10 03:31 UTC, roleyfoley commented on .github/PULL_REQUEST_TEMPLATE.md
>  <!--- Provide a general summary of your changes in the Title above -->
I think this one is pretty self explanatory? Is it required?

2021-03-10 03:31 UTC, roleyfoley commented on .github/PULL_REQUEST_TEMPLATE.md
>  ## How Has This Been Tested?
Can we make these comments shorter or consolidate them down to a single line?

2021-03-10 03:31 UTC, roleyfoley commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--- Review the following checklist to ensure you're Pull Request is complete.               -->
Are you expecting people to answer these in the template? if you are I'm not sure this is required.

2021-04-07 00:20 UTC, roleyfoley approved these changes

2021-04-07 00:20 UTC, merged